services:
  postgres:
    image: postgres:15.4-bullseye
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_management
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '35433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data