CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE TABLE "UserRoles" (
                             "UserRoleId" integer GENERATED BY DEFAULT AS IDENTITY,
                             "Name" text NOT NULL,
                             "CreatedBy" text NOT NULL,
                             "CreatedAt" timestamp with time zone NOT NULL,
                             "UpdatedBy" text NOT NULL,
                             "UpdatedAt" timestamp with time zone NOT NULL,
                             CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserRoleId")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE TABLE "Users" (
                         "UserId" uuid NOT NULL,
                         "Username" text NOT NULL,
                         "EmailAddress" text NOT NULL,
                         "PasswordHash" text NOT NULL,
                         "PasswordSalt" text NOT NULL,
                         "UserRoleId" integer NOT NULL,
                         "CreatedBy" text NOT NULL,
                         "CreatedAt" timestamp with time zone NOT NULL,
                         "UpdatedBy" text NOT NULL,
                         "UpdatedAt" timestamp with time zone NOT NULL,
                         "IsDeleted" boolean NOT NULL,
                         "DeletedBy" text,
                         "DeletedAt" timestamp with time zone,
                         CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
                         CONSTRAINT "FK_Users_UserRoles_UserRoleId" FOREIGN KEY ("UserRoleId") REFERENCES "UserRoles" ("UserRoleId")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE TABLE "Logins" (
                          "LoginId" uuid NOT NULL,
                          "UserId" uuid NOT NULL,
                          "IpAddress" text NOT NULL,
                          "RefreshToken" text NOT NULL,
                          "ExpiresAt" timestamp with time zone NOT NULL,
                          "CreatedBy" text NOT NULL,
                          "CreatedAt" timestamp with time zone NOT NULL,
                          "UpdatedBy" text NOT NULL,
                          "UpdatedAt" timestamp with time zone NOT NULL,
                          "IsRevoked" boolean NOT NULL,
                          "RevokedBy" text,
                          "RevokedAt" timestamp with time zone,
                          CONSTRAINT "PK_Logins" PRIMARY KEY ("LoginId"),
                          CONSTRAINT "FK_Logins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE TABLE "PasswordResets" (
                                  "PasswordResetId" uuid NOT NULL,
                                  "UserId" uuid NOT NULL,
                                  "ResetToken" text NOT NULL,
                                  "IsUsed" boolean NOT NULL,
                                  "CreatedBy" text NOT NULL,
                                  "CreatedAt" timestamp with time zone NOT NULL,
                                  "UpdatedBy" text NOT NULL,
                                  "UpdatedAt" timestamp with time zone NOT NULL,
                                  CONSTRAINT "PK_PasswordResets" PRIMARY KEY ("PasswordResetId"),
                                  CONSTRAINT "FK_PasswordResets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
    INSERT INTO "UserRoles" ("UserRoleId", "CreatedAt", "CreatedBy", "Name", "UpdatedAt", "UpdatedBy")
    VALUES (1, TIMESTAMPTZ '2024-08-26T14:35:16.944998Z', 'System', 'User', TIMESTAMPTZ '2024-08-26T14:35:16.945038Z', 'System');
INSERT INTO "UserRoles" ("UserRoleId", "CreatedAt", "CreatedBy", "Name", "UpdatedAt", "UpdatedBy")
VALUES (2, TIMESTAMPTZ '2024-08-26T14:35:16.945083Z', 'System', 'Admin', TIMESTAMPTZ '2024-08-26T14:35:16.945083Z', 'System');
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
    INSERT INTO "Users" ("UserId", "CreatedAt", "CreatedBy", "DeletedAt", "DeletedBy", "EmailAddress", "IsDeleted", "PasswordHash", "PasswordSalt", "UpdatedAt", "UpdatedBy", "UserRoleId", "Username")
    VALUES ('042d614a-dc7c-4b37-8f77-d1d990c1a4bf', TIMESTAMPTZ '2024-08-26T14:35:16.945385Z', 'System', NULL, NULL, 'admin@admin.com', FALSE, '', '', TIMESTAMPTZ '2024-08-26T14:35:16.945385Z', 'System', 2, 'admin');
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE INDEX "IX_Logins_UserId" ON "Logins" ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE INDEX "IX_PasswordResets_UserId" ON "PasswordResets" ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE UNIQUE INDEX "IX_Users_EmailAddress" ON "Users" ("EmailAddress");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE INDEX "IX_Users_UserRoleId" ON "Users" ("UserRoleId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
    PERFORM setval(
        pg_get_serial_sequence('"UserRoles"', 'UserRoleId'),
        GREATEST(
            (SELECT MAX("UserRoleId") FROM "UserRoles") + 1,
            nextval(pg_get_serial_sequence('"UserRoles"', 'UserRoleId'))),
        false);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240826143517_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240826143517_Initial', '8.0.8');
END IF;
END $EF$;
COMMIT;

