// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(PennyPlannerDbContext))]
    [Migration("20240824221809_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Infrastructure.Entities.LoginEntity", b =>
                {
                    b.Property<Guid>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(18);

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.HasKey("LoginId");

                    b.HasIndex("UserId");

                    b.ToTable("Logins", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.PasswordResetEntity", b =>
                {
                    b.Property<Guid>("PasswordResetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("ResetToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.HasKey("PasswordResetId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(20);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(21);

                    b.Property<int>("UserRoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ea42708d-ab30-4311-bf80-90905c26ae6b"),
                            CreatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 369, DateTimeKind.Utc).AddTicks(2528),
                            EmailAddress = "admin@admin.com",
                            IsDeleted = false,
                            PasswordHash = "",
                            PasswordSalt = "",
                            UpdatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 369, DateTimeKind.Utc).AddTicks(2529),
                            UpdatedBy = "System",
                            UserRoleId = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            CreatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 368, DateTimeKind.Utc).AddTicks(9085),
                            Name = "User",
                            UpdatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 368, DateTimeKind.Utc).AddTicks(9399),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            UserRoleId = 2,
                            CreatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 368, DateTimeKind.Utc).AddTicks(9789),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2024, 8, 24, 22, 18, 9, 368, DateTimeKind.Utc).AddTicks(9790),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.LoginEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.UserEntity", "UserEntity")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Infrastructure.Entities.PasswordResetEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.UserEntity", "UserEntity")
                        .WithMany("PasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserEntity", b =>
                {
                    b.HasOne("Infrastructure.Entities.UserRoleEntity", "UserRoleEntity")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .IsRequired();

                    b.Navigation("UserRoleEntity");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserEntity", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("PasswordResets");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserRoleEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
