name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-bullseye
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_management
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 35433:5432
      smtp:
        image: reachfive/fake-smtp-server
        ports:
          - 1025:1025
          - 1080:1080

    steps:
    - name: Run Migrations
      run: find ./ -name Migration.sql
      # psql -f Migration.sql postgresql://postgres:postgres@localhost:35433/user_management

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger:"trx;LogFileName=test_results.trx"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/*.trx'
