name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_management
        ports:
          - 35433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      smtp:
        image: reachfive/fake-smtp-server
        ports:
          - 1025:1025
          - 1080:1080

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Migration Script
      run: psql -d postgresql://postgres@localhost/user_management -f Migration.sql
      working-directory: src/Infrastructure/Scripts
      env:
        PGPASSWORD: postgres
        PGPORT: 35433

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger:"trx;LogFileName=test_results.trx"

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/*.trx'
